version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

volumes:
  db-store: